name: rounded_background_text
description: Text, TextField and TextSpan highlighted with rounded corners
version: 0.4.3
repository: https://github.com/bdlukaa/rounded_background_text

environment:
  sdk: ">=2.18.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
